### Welcome message

GET http://127.0.0.1:8080/
Accept: application/json

### Health check

GET http://127.0.0.1:8080/health
Accept: application/json

Response 200 OK
Content-Type: application/json

{
  "status": "healthy"
}

### Say hello to User

GET http://127.0.0.1:8080/hello/User
Accept: application/json

Response 200 OK
Content-Type: application/json

{
  "message": "Hello, User!"
}

###
